name: flemby
description: "A cross-platform third-party Emby client."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  bloc: ^9.2.0
  device_info_plus: ^12.3.0
  dio: ^5.9.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^9.2.0
  go_router: ^17.0.1
  intl: any
  json_annotation: ^4.9.0
  logger: ^2.6.2
  meta: ^1.17.0
  package_info_plus: ^9.0.0
  shared_preferences: ^2.5.4
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.4
  build_runner: ^2.10.5

flutter:
  uses-material-design: true
  generate: true
